### ISSUE TITLE
Support for 3.5+?

### ISSUE THREAD

**Issue by shanegriffiths** [wonderbit/sketch-select-similar-layers#3]
Is this plugin supported on 3.5+?

Many thanks
S

**Comment by wonderbit** [comment]
Yes it is! :)

**Comment by RaphyRaph** [comment]
Select same font doesn't work for me. Screencap here: http://cl.ly/3u0q0E241g1M

_EDIT_ I understand now: it's because it's looking in the same artboard. I'll change the cocoascript to have a broader scope. You might want to add an option to expand the scope. i.e. , if you don't find similar layers in the current artboard, show dialog "no similar layers found on artboard, expand to all artboards? yes/no") This would make it clear what it's doing, and offer a fallback.

**Comment by wonderbit** [comment]
@RaphyRaph That's actually a great idea. Will add this to the improvements bucket :)

**Comment by Rmohan06** [comment]
@wonderbit any plans to add this expand scope feature soon? It would be such a great addition as I have a bunch of symbols that sit within their own artboards that I am not able to mass update with this plugin. 

Thanks!

**Comment by wonderbit** [comment]
@Rmohan06 I know it's not ideal but if you can edit the code of the plug-in, you'll see this declaration in line 6: "var selectInAllArtboards = false;"… change that "false" to "true" and it'll select from multiple artboards. Will work on @RaphyRaph 's idea soon…
